[package]
name = "viewer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
obsidian = {path = ".."}
anyhow = "1.0.34"
log = "0.4.11"
obsidian_render = {path = "crates/obsidian_render"}