[package]
name = "obsidian"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["crates/*", "viewer"]
default-members = ["viewer"]

[dependencies]
obsidian_app = { path = "crates/obsidian_app" }
obsidian_render = { path = "crates/obsidian_render" }
